from enum import StrEnum


class AuditAction(StrEnum):
    LOGIN = "auth.login"
    LOGOUT = "auth.logout"
    USER_CREATE = "settings.user.create"
    ROLE_PERMISSION_UPDATE = "settings.role.permissions.update"
    PATIENT_CREATE = "patient.create"
    BILLING_SERVICE_CREATE = "billing.service.create"
    BILLING_DOCTOR_CREATE = "billing.doctor.create"
    BILLING_SETTINGS_UPDATE = "billing.settings.update"
    BILLING_INVOICE_CREATE = "billing.invoice.create"
    BILLING_INVOICE_VOID = "billing.invoice.void"
    BILLING_PAYMENT_CREATE = "billing.payment.create"
    BILLING_REFUND_CREATE = "billing.refund.create"
    OPD_VISIT_CREATE = "opd.visit.create"
    OPD_VISIT_STATUS_UPDATE = "opd.visit.status.update"
    OPD_VISIT_ORDER_CREATE = "opd.visit.order.create"
    OPD_VISIT_ORDER_UPDATE = "opd.visit.order.update"
    OPD_INVESTIGATION_RESULT_UPDATE = "opd.investigation.result.update"
    IPD_ADMISSION_CREATE = "ipd.admission.create"
    IPD_ADMISSION_DISCHARGE = "ipd.admission.discharge"
    IPD_ADMISSION_TRANSFER = "ipd.admission.transfer"
    IPD_BED_CREATE = "ipd.bed.create"
    PHARMACY_DISPENSE = "pharmacy.dispense"
    ACCOUNTING_POST = "accounting.journal.post"
