PERMISSION_CATALOG = [
    ("dashboard.view", "dashboard", "view", "View dashboard"),
    ("patient.view", "patient", "view", "View patients"),
    ("patient.create", "patient", "create", "Create patients"),
    ("patient.portal.view", "patient", "portal.view", "Access patient portal"),
    ("patient.edit", "patient", "edit", "Edit patients"),
    ("patient.delete", "patient", "delete", "Delete patients"),
    ("patient.medical_record.update", "patient", "medical_record.update", "Update patient medical records"),
    ("appointment.view", "appointment", "view", "View appointments"),
    ("appointment.book", "appointment", "book", "Book appointments"),
    ("appointment.manage", "appointment", "manage", "Manage and check in appointments"),
    ("appointment.cancel", "appointment", "cancel", "Cancel appointments"),
    ("billing.view", "billing", "view", "View billing"),
    ("billing.invoice.create", "billing", "invoice.create", "Create billing invoices"),
    ("billing.item.service", "billing", "item.service", "Bill general service catalog items"),
    ("billing.item.medicine", "billing", "item.medicine", "Bill pharmacy medicine items"),
    ("billing.item.investigation", "billing", "item.investigation", "Bill laboratory and radiology investigation items"),
    ("billing.invoice.void", "billing", "invoice.void", "Void billing invoices"),
    ("billing.payment.collect", "billing", "payment.collect", "Collect billing payments"),
    ("billing.payment.refund", "billing", "payment.refund", "Refund billing payments"),
    ("billing.sticker.print", "billing", "sticker.print", "Print billing and investigation token stickers"),
    ("billing.service.manage", "billing", "service.manage", "Manage billing services"),
    ("billing.doctor.manage", "billing", "doctor.manage", "Manage referred doctors"),
    ("opd.view", "opd", "view", "View OPD module"),
    ("opd.view.doctor_wise", "opd", "view.doctor_wise", "View doctor-wise OPD queues"),
    ("opd.visit.create", "opd", "visit.create", "Create OPD visits"),
    ("opd.visit.edit", "opd", "visit.edit", "Edit OPD visit details"),
    ("opd.visit.manage", "opd", "visit.manage", "Manage OPD visits"),
    ("opd.visit.cancel", "opd", "visit.cancel", "Cancel OPD visits"),
    ("opd.prescribe", "opd", "prescribe", "Prescribe medicines and update OPD consultation records"),
    ("opd.settings.manage", "opd", "settings.manage", "Manage OPD doctor setup, fee sharing, prescription suggestions, and OPD print layouts"),
    ("ipd.view", "ipd", "view", "View IPD module"),
    ("ipd.admit", "ipd", "admit", "Admit patients to IPD"),
    ("ipd.admission.manage", "ipd", "admission.manage", "Manage IPD admissions"),
    ("ipd.discharge", "ipd", "discharge", "Discharge IPD patients"),
    ("ipd.transfer", "ipd", "transfer", "Transfer IPD patients and beds"),
    ("ipd.bed.manage", "ipd", "bed.manage", "Manage IPD beds"),
    ("er.view", "er", "view", "View emergency room module"),
    ("emergency.view", "emergency", "view", "View emergency department command center"),
    ("emergency.register", "emergency", "register", "Register emergency patients"),
    ("emergency.triage", "emergency", "triage", "Perform emergency triage"),
    ("emergency.retriage", "emergency", "retriage", "Repeat emergency triage when condition changes"),
    ("emergency.assess", "emergency", "assess", "Document emergency doctor assessment"),
    ("emergency.order.create", "emergency", "order.create", "Create emergency orders"),
    ("emergency.medication.administer", "emergency", "medication.administer", "Record emergency medication administration"),
    ("emergency.bed.assign", "emergency", "bed.assign", "Assign emergency bed or zone"),
    ("emergency.status.update", "emergency", "status.update", "Update emergency patient status"),
    ("emergency.disposition", "emergency", "disposition", "Finalize emergency disposition"),
    ("emergency.discharge", "emergency", "discharge", "Discharge emergency patients"),
    ("emergency.transfer", "emergency", "transfer", "Transfer emergency patients"),
    ("emergency.report.print", "emergency", "report.print", "Print emergency reports"),
    ("emergency.delete", "emergency", "delete", "Delete emergency records"),
    ("er.visit.manage", "er", "visit.manage", "Manage emergency room visits"),
    ("er.triage.manage", "er", "triage.manage", "Manage ER triage workflows"),
    ("er.assignment.manage", "er", "assignment.manage", "Manage ER assignments"),
    ("er.ambulance.manage", "er", "ambulance.manage", "Manage ambulance handoff records"),
    ("laboratory.view", "laboratory", "view", "View laboratory"),
    ("laboratory.manage", "laboratory", "manage", "Manage laboratory worklist and results"),
    ("laboratory.order.create", "laboratory", "order.create", "Create laboratory orders"),
    ("laboratory.result.enter", "laboratory", "result.enter", "Enter laboratory results"),
    ("laboratory.verify_result", "laboratory", "verify_result", "Verify laboratory results"),
    ("laboratory.report.print", "laboratory", "report.print", "Print laboratory reports"),
    ("radiology.view", "radiology", "view", "View radiology"),
    ("radiology.manage", "radiology", "manage", "Manage radiology worklist and results"),
    ("radiology.order.create", "radiology", "order.create", "Create radiology orders"),
    ("radiology.upload_image", "radiology", "upload_image", "Upload or link radiology images and PACS studies"),
    ("radiology.upload_report", "radiology", "upload_report", "Upload and edit radiology reports"),
    ("radiology.verify_result", "radiology", "verify_result", "Verify radiology results"),
    ("radiology.report.print", "radiology", "report.print", "Print radiology reports"),
    ("diagnostics.view", "diagnostics", "view", "View diagnostic orders and settings"),
    ("diagnostics.order.manage", "diagnostics", "order.manage", "Manage diagnostic orders"),
    ("diagnostics.settings.manage", "diagnostics", "settings.manage", "Manage diagnostic settings"),
    ("reporting.view", "reporting", "view", "View reporting"),
    ("reporting.export", "reporting", "export", "Export reports"),
    ("reporting.financial.view", "reporting", "financial.view", "View financial reports and revenue analytics"),
    ("pharmacy.view", "pharmacy", "view", "View pharmacy module"),
    ("pharmacy.dispense", "pharmacy", "dispense", "Dispense medicine"),
    ("pharmacy.sale.create", "pharmacy", "sale.create", "Create pharmacy sales"),
    ("pharmacy.return", "pharmacy", "return", "Process pharmacy returns"),
    ("pharmacy.stock.adjust", "pharmacy", "stock.adjust", "Adjust pharmacy stock"),
    ("pharmacy.purchase.manage", "pharmacy", "purchase.manage", "Manage pharmacy purchases"),
    ("pharmacy.settings.manage", "pharmacy", "settings.manage", "Manage pharmacy master data and settings"),
    ("inventory.view", "inventory", "view", "View inventory module"),
    ("inventory.manage", "inventory", "manage", "Manage inventory items and suppliers"),
    ("inventory.item.create", "inventory", "item.create", "Create inventory items and suppliers"),
    ("inventory.item.edit", "inventory", "item.edit", "Edit inventory items and suppliers"),
    ("inventory.receive", "inventory", "receive", "Receive inventory stock"),
    ("inventory.issue", "inventory", "issue", "Issue inventory stock"),
    ("inventory.transfer", "inventory", "transfer", "Transfer inventory stock"),
    ("inventory.adjust", "inventory", "adjust", "Adjust inventory stock"),
    ("inventory.stock.receive", "inventory", "stock.receive", "Receive stock into stores"),
    ("inventory.stock.issue", "inventory", "stock.issue", "Issue stock from stores"),
    ("inventory.stock.transfer", "inventory", "stock.transfer", "Transfer stock between stores"),
    ("inventory.stock.adjust", "inventory", "stock.adjust", "Adjust stock balances"),
    ("inventory.purchase", "inventory", "purchase", "Manage purchase requests"),
    ("inventory.requisition.create", "inventory", "requisition.create", "Create store requisitions"),
    ("inventory.requisition.approve", "inventory", "requisition.approve", "Approve and issue store requisitions"),
    ("inventory.requisition.reject", "inventory", "requisition.reject", "Reject store requisitions"),
    ("inventory.reports.view", "inventory", "reports.view", "View inventory reports"),
    ("inventory.report.view", "inventory", "report.view", "View inventory reports"),
    ("inventory.store.manage", "inventory", "store.manage", "Manage central and sub stores"),
    ("inventory.export", "inventory", "export", "Export inventory reports"),
    ("hr.view", "hr", "view", "View HR and payroll module"),
    ("hr.employee.manage", "hr", "employee.manage", "Manage employee profiles, departments, and designations"),
    ("hr.attendance.manage", "hr", "attendance.manage", "Manage attendance and attendance corrections"),
    ("hr.shift.manage", "hr", "shift.manage", "Manage shifts and duty rosters"),
    ("hr.leave.manage", "hr", "leave.manage", "Manage leave requests and balances"),
    ("hr.leave.approve", "hr", "leave.approve", "Approve or reject leave requests"),
    ("hr.payroll.manage", "hr", "payroll.manage", "Manage salary setup, overtime, loans, payroll runs, and payslips"),
    ("hr.payroll.approve", "hr", "payroll.approve", "Approve, finalize, and mark payroll paid"),
    ("payroll.process_salary", "payroll", "process_salary", "Process payroll salary runs"),
    ("payroll.view", "payroll", "view", "View payroll data"),
    ("hr.recruitment.manage", "hr", "recruitment.manage", "Manage recruitment and onboarding"),
    ("hr.performance.manage", "hr", "performance.manage", "Manage performance, appraisal, and disciplinary records"),
    ("hr.exit.manage", "hr", "exit.manage", "Manage resignation, exit, and final settlement"),
    ("hr.documents.manage", "hr", "documents.manage", "Manage HR documents and letters"),
    ("hr.reports.view", "hr", "reports.view", "View HR and payroll reports"),
    ("hr.settings.manage", "hr", "settings.manage", "Manage HR module settings"),
    ("hr.self_service", "hr", "self_service", "Use employee self-service HR features"),
    ("ot.view", "ot", "view", "View OT management module"),
    ("ot.room.manage", "ot", "room.manage", "Manage OT rooms and room status"),
    ("ot.booking.manage", "ot", "booking.manage", "Create and approve OT booking requests"),
    ("ot.schedule.manage", "ot", "schedule.manage", "Schedule surgeries and assign OT staff"),
    ("ot.preop.manage", "ot", "preop.manage", "Manage pre-operative checklist and readiness"),
    ("ot.anesthesia.manage", "ot", "anesthesia.manage", "Manage anesthesia assessment, records, and sign-off"),
    ("ot.surgery.signoff", "ot", "surgery.signoff", "Manage operative notes and surgical sign-off"),
    ("ot.recovery.manage", "ot", "recovery.manage", "Manage post-operative recovery and handover"),
    ("ot.inventory.manage", "ot", "inventory.manage", "Manage OT consumables, equipment, implants, and usage"),
    ("ot.billing.manage", "ot", "billing.manage", "Manage OT billing items and charge summary"),
    ("ot.documents.manage", "ot", "documents.manage", "Manage OT consent, forms, and documents"),
    ("ot.workflow.manage", "ot", "workflow.manage", "Start, complete, cancel, and update surgery workflow status"),
    ("ot.reports.view", "ot", "reports.view", "View OT reports and analytics"),
    ("accounting.view", "accounting", "view", "View accounting"),
    ("accounting.manage", "accounting", "manage", "Manage accounting workflows"),
    ("accounting.approve", "accounting", "approve", "Approve discounts, refunds, expenses, payables, and closings"),
    ("accounting.reports.view", "accounting", "reports.view", "View accounting and finance reports"),
    ("accounting.journal.create", "accounting", "journal.create", "Create accounting journal"),
    ("accounting.journal.post", "accounting", "journal.post", "Post accounting journal"),
    ("settings.user.manage", "settings", "user.manage", "Manage users"),
    ("settings.role.manage", "settings", "role.manage", "Manage roles"),
    ("settings.permission.manage", "settings", "permission.manage", "Manage permission catalog"),
    ("admin.manage_users", "admin", "manage_users", "Manage administrative user accounts"),
    ("admin.manage_roles", "admin", "manage_roles", "Manage administrative roles and permissions"),
    ("settings.branch.manage", "settings", "branch.manage", "Manage branches"),
    ("settings.department.manage", "settings", "department.manage", "Manage departments"),
    ("settings.configuration.manage", "settings", "configuration.manage", "Manage hospital configuration builders and setup profiles"),
    ("audit.view", "audit", "view", "View audit logs"),
]

ROLE_CATALOG = {
    "SUPER_ADMIN": [code for code, *_ in PERMISSION_CATALOG],
    "ADMIN": [code for code, *_ in PERMISSION_CATALOG],
    "DOCTOR": [
        "dashboard.view",
        "patient.view",
        "patient.create",
        "patient.medical_record.update",
        "appointment.view",
        "appointment.book",
        "appointment.manage",
        "opd.view",
        "opd.visit.create",
        "opd.visit.edit",
        "opd.visit.manage",
        "opd.prescribe",
        "ipd.view",
        "ipd.admit",
        "ipd.bed.manage",
        "ipd.transfer",
        "ipd.discharge",
        "er.view",
        "er.visit.manage",
        "er.triage.manage",
        "er.assignment.manage",
        "er.ambulance.manage",
        "laboratory.view",
        "laboratory.manage",
        "laboratory.order.create",
        "laboratory.result.enter",
        "laboratory.verify_result",
        "laboratory.report.print",
        "radiology.view",
        "radiology.manage",
        "radiology.order.create",
        "radiology.upload_report",
        "radiology.verify_result",
        "radiology.report.print",
        "diagnostics.view",
        "diagnostics.order.manage",
        "reporting.view",
        "ot.view",
        "ot.booking.manage",
        "ot.surgery.signoff",
        "ot.reports.view",
    ],
    "OT_MANAGER": [
        "dashboard.view",
        "patient.view",
        "ipd.view",
        "er.view",
        "ot.view",
        "ot.room.manage",
        "ot.booking.manage",
        "ot.schedule.manage",
        "ot.preop.manage",
        "ot.workflow.manage",
        "ot.documents.manage",
        "ot.reports.view",
    ],
    "SURGEON": [
        "dashboard.view",
        "patient.view",
        "ot.view",
        "ot.booking.manage",
        "ot.surgery.signoff",
        "ot.reports.view",
    ],
    "ANESTHETIST": [
        "dashboard.view",
        "patient.view",
        "ot.view",
        "ot.anesthesia.manage",
        "ot.reports.view",
    ],
    "OT_NURSE": [
        "dashboard.view",
        "patient.view",
        "ot.view",
        "ot.preop.manage",
        "ot.recovery.manage",
        "ot.workflow.manage",
        "ot.surgery.signoff",
    ],
    "OT_BILLING_OFFICER": [
        "dashboard.view",
        "patient.view",
        "ot.view",
        "ot.billing.manage",
        "billing.view",
        "billing.invoice.create",
        "billing.payment.collect",
    ],
    "HR_MANAGER": [
        "dashboard.view",
        "patient.view",
        "hr.view",
        "hr.employee.manage",
        "hr.attendance.manage",
        "hr.shift.manage",
        "hr.leave.manage",
        "hr.leave.approve",
        "hr.payroll.manage",
        "payroll.view",
        "payroll.process_salary",
        "hr.recruitment.manage",
        "hr.performance.manage",
        "hr.exit.manage",
        "hr.documents.manage",
        "hr.reports.view",
        "hr.settings.manage",
        "settings.department.manage",
    ],
    "PAYROLL_OFFICER": [
        "dashboard.view",
        "hr.view",
        "hr.payroll.manage",
        "payroll.view",
        "payroll.process_salary",
        "hr.reports.view",
        "accounting.view",
    ],
    "DEPARTMENT_HEAD": [
        "dashboard.view",
        "patient.view",
        "hr.view",
        "hr.attendance.manage",
        "hr.shift.manage",
        "hr.leave.manage",
        "hr.leave.approve",
        "hr.reports.view",
    ],
    "EMPLOYEE": [
        "dashboard.view",
        "hr.view",
        "hr.self_service",
        "hr.leave.manage",
    ],
    "REFERRABLE_DOCTOR": [
        "dashboard.view",
        "patient.view",
        "appointment.view",
        "opd.view",
        "ipd.view",
        "laboratory.view",
        "radiology.view",
        "diagnostics.view",
        "reporting.view",
        "billing.view",
    ],
    "RECEPTIONIST": [
        "dashboard.view",
        "patient.view",
        "patient.create",
        "appointment.view",
        "appointment.book",
        "appointment.manage",
        "appointment.cancel",
        "opd.view",
        "opd.visit.create",
        "opd.visit.edit",
        "billing.view",
        "billing.invoice.create",
        "billing.item.service",
        "billing.item.investigation",
        "billing.payment.collect",
        "billing.sticker.print",
    ],
    "LAB_TECHNICIAN": [
        "dashboard.view",
        "patient.view",
        "laboratory.view",
        "laboratory.manage",
        "laboratory.result.enter",
        "laboratory.verify_result",
        "laboratory.report.print",
        "diagnostics.view",
        "diagnostics.order.manage",
        "inventory.view",
    ],
    "RADIOLOGY_TECHNICIAN": [
        "dashboard.view",
        "patient.view",
        "radiology.view",
        "radiology.manage",
        "radiology.order.create",
        "radiology.upload_image",
        "radiology.upload_report",
        "radiology.verify_result",
        "radiology.report.print",
        "diagnostics.view",
        "diagnostics.order.manage",
    ],
    "INVENTORY_MANAGER": [
        "dashboard.view",
        "inventory.view",
        "inventory.manage",
        "inventory.item.create",
        "inventory.item.edit",
        "inventory.receive",
        "inventory.issue",
        "inventory.transfer",
        "inventory.adjust",
        "inventory.stock.receive",
        "inventory.stock.issue",
        "inventory.stock.transfer",
        "inventory.stock.adjust",
        "inventory.purchase",
        "inventory.requisition.create",
        "inventory.requisition.approve",
        "inventory.requisition.reject",
        "inventory.reports.view",
        "inventory.report.view",
        "inventory.store.manage",
        "inventory.export",
        "pharmacy.view",
    ],
    "PATIENT": [
        "patient.portal.view",
        "appointment.view",
        "appointment.book",
    ],
    "PHARMACIST": [
        "dashboard.view",
        "patient.view",
        "pharmacy.view",
        "pharmacy.dispense",
        "pharmacy.sale.create",
        "pharmacy.return",
        "pharmacy.stock.adjust",
        "pharmacy.purchase.manage",
        "pharmacy.settings.manage",
    ],
    "ACCOUNTANT": [
        "dashboard.view",
        "billing.view",
        "billing.invoice.create",
        "billing.item.service",
        "billing.item.medicine",
        "billing.item.investigation",
        "billing.invoice.void",
        "billing.payment.collect",
        "billing.payment.refund",
        "billing.sticker.print",
        "billing.service.manage",
        "billing.doctor.manage",
        "reporting.view",
        "reporting.financial.view",
        "reporting.export",
        "accounting.view",
        "accounting.manage",
        "accounting.approve",
        "accounting.reports.view",
        "accounting.journal.create",
        "accounting.journal.post",
        "diagnostics.view",
        "hr.view",
        "hr.payroll.manage",
        "payroll.view",
        "payroll.process_salary",
        "hr.reports.view",
        "ot.view",
        "ot.billing.manage",
        "ot.reports.view",
    ],
}

ROLE_FLAGS = {
    "SUPER_ADMIN": {"is_doctor_role": False, "is_referral_role": False},
    "ADMIN": {"is_doctor_role": False, "is_referral_role": False},
    "DOCTOR": {"is_doctor_role": True, "is_referral_role": True},
    "REFERRABLE_DOCTOR": {"is_doctor_role": True, "is_referral_role": True},
    "PHARMACIST": {"is_doctor_role": False, "is_referral_role": False},
    "ACCOUNTANT": {"is_doctor_role": False, "is_referral_role": False},
    "RECEPTIONIST": {"is_doctor_role": False, "is_referral_role": False},
    "LAB_TECHNICIAN": {"is_doctor_role": False, "is_referral_role": False},
    "RADIOLOGY_TECHNICIAN": {"is_doctor_role": False, "is_referral_role": False},
    "INVENTORY_MANAGER": {"is_doctor_role": False, "is_referral_role": False},
    "HR_MANAGER": {"is_doctor_role": False, "is_referral_role": False},
    "PAYROLL_OFFICER": {"is_doctor_role": False, "is_referral_role": False},
    "DEPARTMENT_HEAD": {"is_doctor_role": False, "is_referral_role": False},
    "EMPLOYEE": {"is_doctor_role": False, "is_referral_role": False},
    "OT_MANAGER": {"is_doctor_role": False, "is_referral_role": False},
    "SURGEON": {"is_doctor_role": True, "is_referral_role": True},
    "ANESTHETIST": {"is_doctor_role": True, "is_referral_role": False},
    "OT_NURSE": {"is_doctor_role": False, "is_referral_role": False},
    "OT_BILLING_OFFICER": {"is_doctor_role": False, "is_referral_role": False},
    "PATIENT": {"is_doctor_role": False, "is_referral_role": False},
}
