PERMISSION_CATALOG = [
    ("dashboard.view", "dashboard", "view", "View dashboard"),
    ("patient.view", "patient", "view", "View patients"),
    ("patient.create", "patient", "create", "Create patients"),
    ("patient.portal.view", "patient", "portal.view", "Access patient portal"),
    ("patient.edit", "patient", "edit", "Edit patients"),
    ("patient.delete", "patient", "delete", "Delete patients"),
    ("patient.medical_record.update", "patient", "medical_record.update", "Update patient medical records"),
    ("patient.id_card.view", "patient", "id_card.view", "View patient ID card preview"),
    ("patient.id_card.generate", "patient", "id_card.generate", "Generate patient ID card barcode"),
    ("patient.id_card.print", "patient", "id_card.print", "Print patient ID card"),
    ("patient.id_card.reprint", "patient", "id_card.reprint", "Reprint patient ID card"),
    ("patient.id_card.configure", "patient", "id_card.configure", "Configure patient ID card template"),
    ("appointment.view", "appointment", "view", "View appointments"),
    ("appointment.book", "appointment", "book", "Book appointments"),
    ("appointment.manage", "appointment", "manage", "Manage and check in appointments"),
    ("appointment.cancel", "appointment", "cancel", "Cancel appointments"),
    ("billing.view", "billing", "view", "View billing"),
    ("billing.invoice.create", "billing", "invoice.create", "Create billing invoices"),
    ("billing.item.service", "billing", "item.service", "Bill general service catalog items"),
    ("billing.item.medicine", "billing", "item.medicine", "Bill pharmacy medicine items"),
    ("billing.item.investigation", "billing", "item.investigation", "Bill laboratory and radiology investigation items"),
    ("billing.invoice.void", "billing", "invoice.void", "Void billing invoices"),
    ("billing.payment.collect", "billing", "payment.collect", "Collect billing payments"),
    ("billing.payment.refund", "billing", "payment.refund", "Refund billing payments"),
    ("billing.sticker.print", "billing", "sticker.print", "Print billing and investigation token stickers"),
    ("billing.service.manage", "billing", "service.manage", "Manage billing services"),
    ("billing.doctor.manage", "billing", "doctor.manage", "Manage referred doctors"),
    ("opd.view", "opd", "view", "View OPD module"),
    ("opd.view.doctor_wise", "opd", "view.doctor_wise", "View doctor-wise OPD queues"),
    ("opd.visit.create", "opd", "visit.create", "Create OPD visits"),
    ("opd.visit.edit", "opd", "visit.edit", "Edit OPD visit details"),
    ("opd.visit.manage", "opd", "visit.manage", "Manage OPD visits"),
    ("opd.visit.cancel", "opd", "visit.cancel", "Cancel OPD visits"),
    ("opd.prescribe", "opd", "prescribe", "Prescribe medicines and update OPD consultation records"),
    ("opd.settings.manage", "opd", "settings.manage", "Manage OPD doctor setup, fee sharing, prescription suggestions, and OPD print layouts"),
    ("ipd.view", "ipd", "view", "View IPD module"),
    ("ipd.admit", "ipd", "admit", "Admit patients to IPD"),
    ("ipd.admission.manage", "ipd", "admission.manage", "Manage IPD admissions"),
    ("ipd.discharge", "ipd", "discharge", "Discharge IPD patients"),
    ("ipd.transfer", "ipd", "transfer", "Transfer IPD patients and beds"),
    ("ipd.bed.manage", "ipd", "bed.manage", "Manage IPD beds"),
    ("ipd.settings.manage", "ipd", "settings.manage", "Manage IPD workflow and policy settings"),
    ("ipd.edit_admission", "ipd", "edit_admission", "Edit IPD admission details"),
    ("ipd.assign_doctor", "ipd", "assign_doctor", "Assign or change IPD doctors"),
    ("ipd.assign_nurse", "ipd", "assign_nurse", "Assign or change IPD nurses"),
    ("ipd.bed_transfer", "ipd", "bed_transfer", "Transfer IPD beds"),
    ("ipd.doctor_note.create", "ipd", "doctor_note.create", "Create IPD doctor notes"),
    ("ipd.nursing_note.create", "ipd", "nursing_note.create", "Create IPD nursing notes and vitals"),
    ("ipd.order.create", "ipd", "order.create", "Create IPD orders"),
    ("ipd.medication.administer", "ipd", "medication.administer", "Administer IPD medicines"),
    ("ipd.handover.create", "ipd", "handover.create", "Create duty handovers"),
    ("ipd.handover.acknowledge", "ipd", "handover.acknowledge", "Acknowledge duty handovers"),
    ("ipd.discharge.request", "ipd", "discharge.request", "Request or plan IPD discharge"),
    ("ipd.discharge.approve", "ipd", "discharge.approve", "Approve IPD discharge"),
    ("ipd.discharge.finalize", "ipd", "discharge.finalize", "Finalize IPD discharge"),
    ("ipd.report.print", "ipd", "report.print", "Print IPD reports and summaries"),
    ("er.view", "er", "view", "View emergency room module"),
    ("emergency.view", "emergency", "view", "View emergency department command center"),
    ("emergency.register", "emergency", "register", "Register emergency patients"),
    ("emergency.triage", "emergency", "triage", "Perform emergency triage"),
    ("emergency.retriage", "emergency", "retriage", "Repeat emergency triage when condition changes"),
    ("emergency.assess", "emergency", "assess", "Document emergency doctor assessment"),
    ("emergency.order.create", "emergency", "order.create", "Create emergency orders"),
    ("emergency.medication.administer", "emergency", "medication.administer", "Record emergency medication administration"),
    ("emergency.bed.assign", "emergency", "bed.assign", "Assign emergency bed or zone"),
    ("emergency.status.update", "emergency", "status.update", "Update emergency patient status"),
    ("emergency.disposition", "emergency", "disposition", "Finalize emergency disposition"),
    ("emergency.discharge", "emergency", "discharge", "Discharge emergency patients"),
    ("emergency.transfer", "emergency", "transfer", "Transfer emergency patients"),
    ("emergency.report.print", "emergency", "report.print", "Print emergency reports"),
    ("emergency.delete", "emergency", "delete", "Delete emergency records"),
    ("er.visit.manage", "er", "visit.manage", "Manage emergency room visits"),
    ("er.triage.manage", "er", "triage.manage", "Manage ER triage workflows"),
    ("er.assignment.manage", "er", "assignment.manage", "Manage ER assignments"),
    ("er.ambulance.manage", "er", "ambulance.manage", "Manage ambulance handoff records"),
    ("laboratory.view", "laboratory", "view", "View laboratory"),
    ("laboratory.manage", "laboratory", "manage", "Manage laboratory worklist and results"),
    ("laboratory.order.create", "laboratory", "order.create", "Create laboratory orders"),
    ("laboratory.result.enter", "laboratory", "result.enter", "Enter laboratory results"),
    ("laboratory.verify_result", "laboratory", "verify_result", "Verify laboratory results"),
    ("laboratory.report.print", "laboratory", "report.print", "Print laboratory reports"),
    ("radiology.view", "radiology", "view", "View radiology"),
    ("radiology.manage", "radiology", "manage", "Manage radiology worklist and results"),
    ("radiology.order.create", "radiology", "order.create", "Create radiology orders"),
    ("radiology.upload_image", "radiology", "upload_image", "Upload or link radiology images and PACS studies"),
    ("radiology.upload_report", "radiology", "upload_report", "Upload and edit radiology reports"),
    ("radiology.verify_result", "radiology", "verify_result", "Verify radiology results"),
    ("radiology.report.print", "radiology", "report.print", "Print radiology reports"),
    ("diagnostics.view", "diagnostics", "view", "View diagnostic orders and settings"),
    ("diagnostics.order.manage", "diagnostics", "order.manage", "Manage diagnostic orders"),
    ("diagnostics.settings.manage", "diagnostics", "settings.manage", "Manage diagnostic settings"),
    ("reporting.view", "reporting", "view", "View reporting"),
    ("reporting.export", "reporting", "export", "Export reports"),
    ("reporting.financial.view", "reporting", "financial.view", "View financial reports and revenue analytics"),
    ("pharmacy.view", "pharmacy", "view", "View pharmacy module"),
    ("pharmacy.dispense", "pharmacy", "dispense", "Dispense medicine"),
    ("pharmacy.sale.create", "pharmacy", "sale.create", "Create pharmacy sales"),
    ("pharmacy.return", "pharmacy", "return", "Process pharmacy returns"),
    ("pharmacy.stock.adjust", "pharmacy", "stock.adjust", "Adjust pharmacy stock"),
    ("pharmacy.purchase.manage", "pharmacy", "purchase.manage", "Manage pharmacy purchases"),
    ("pharmacy.settings.manage", "pharmacy", "settings.manage", "Manage pharmacy master data and settings"),
    ("blood_bank.view", "blood_bank", "view", "View blood bank module"),
    ("blood_bank.dashboard.view", "blood_bank", "dashboard.view", "View blood bank dashboard"),
    ("blood_bank.donor.create", "blood_bank", "donor.create", "Register blood donors"),
    ("blood_bank.donor.edit", "blood_bank", "donor.edit", "Edit blood donor profiles"),
    ("blood_bank.donor.screen", "blood_bank", "donor.screen", "Screen blood donors and record eligibility"),
    ("blood_bank.collection.create", "blood_bank", "collection.create", "Collect donor blood and create units"),
    ("blood_bank.testing.update", "blood_bank", "testing.update", "Update blood screening and test results"),
    ("blood_bank.component.prepare", "blood_bank", "component.prepare", "Prepare blood components and manage storage"),
    ("blood_bank.stock.view", "blood_bank", "stock.view", "View blood stock"),
    ("blood_bank.request.create", "blood_bank", "request.create", "Create blood requests"),
    ("blood_bank.request.approve", "blood_bank", "request.approve", "Approve blood requests"),
    ("blood_bank.crossmatch.perform", "blood_bank", "crossmatch.perform", "Perform blood crossmatch"),
    ("blood_bank.crossmatch.verify", "blood_bank", "crossmatch.verify", "Verify blood crossmatch"),
    ("blood_bank.issue", "blood_bank", "issue", "Issue blood units"),
    ("blood_bank.return", "blood_bank", "return", "Return blood units"),
    ("blood_bank.discard", "blood_bank", "discard", "Discard unusable blood units"),
    ("blood_bank.transfusion.update", "blood_bank", "transfusion.update", "Update transfusion events"),
    ("blood_bank.report.view", "blood_bank", "report.view", "View blood bank reports"),
    ("blood_bank.report.export", "blood_bank", "report.export", "Export blood bank reports"),
    ("catering.view", "catering", "view", "View catering module"),
    ("catering.dashboard.view", "catering", "dashboard.view", "View catering dashboard"),
    ("catering.diet_order.create", "catering", "diet_order.create", "Create patient diet orders"),
    ("catering.diet_order.edit", "catering", "diet_order.edit", "Edit patient diet orders"),
    ("catering.diet_order.approve", "catering", "diet_order.approve", "Approve special diet orders"),
    ("catering.kitchen_queue.view", "catering", "kitchen_queue.view", "View kitchen meal queue"),
    ("catering.meal.prepare", "catering", "meal.prepare", "Prepare and update meals"),
    ("catering.meal.deliver", "catering", "meal.deliver", "Deliver meals"),
    ("catering.meal.cancel", "catering", "meal.cancel", "Cancel or hold meals"),
    ("catering.staff_meal.manage", "catering", "staff_meal.manage", "Manage staff meals"),
    ("catering.settings.manage", "catering", "settings.manage", "Manage catering settings"),
    ("catering.report.view", "catering", "report.view", "View catering reports"),
    ("catering.report.export", "catering", "report.export", "Export catering reports"),
    ("scanner.use", "scanner", "use", "Use global barcode and QR scanning"),
    ("scanner.generate", "scanner", "generate", "Generate barcode and QR codes for permitted records"),
    ("scanner.settings.manage", "scanner", "settings.manage", "Manage barcode, QR, label, wristband, and scanner settings"),
    ("scanner.audit.view", "scanner", "audit.view", "View barcode and QR scan audit logs"),
    ("ai.assistant.use", "ai", "assistant.use", "Use the permission-aware hospital AI assistant"),
    ("ai.assistant.action", "ai", "assistant.action", "Allow AI-assisted safe workflow actions"),
    ("ai.assistant.configure", "ai", "assistant.configure", "Configure hospital AI assistant settings"),
    ("ai.assistant.audit.view", "ai", "assistant.audit.view", "View AI assistant audit logs"),
    ("notification.view", "notification", "view", "View role-based notification center"),
    ("notification.action", "notification", "action", "Take permitted actions from notifications"),
    ("notification.configure", "notification", "configure", "Configure hospital notification rules and channels"),
    ("notification.audit.view", "notification", "audit.view", "View notification audit logs"),
    ("queue.view", "queue", "view", "View hospital queue dashboard and tokens"),
    ("queue.call_next", "queue", "call_next", "Call next patient from a queue counter"),
    ("queue.skip", "queue", "skip", "Skip queue token"),
    ("queue.recall", "queue", "recall", "Recall queue token"),
    ("queue.transfer", "queue", "transfer", "Transfer token between queues"),
    ("queue.priority.update", "queue", "priority.update", "Update queue priority"),
    ("queue.counter.manage", "queue", "counter.manage", "Manage queue counters and settings"),
    ("queue.display.manage", "queue", "display.manage", "Manage queue public display screens"),
    ("opd.queue.view", "queue", "opd.view", "View OPD queue"),
    ("opd.queue.call", "queue", "opd.call", "Call OPD queue patients"),
    ("billing.queue.manage", "queue", "billing.manage", "Manage billing queue"),
    ("pharmacy.queue.manage", "queue", "pharmacy.manage", "Manage pharmacy queue"),
    ("lab.queue.manage", "queue", "lab.manage", "Manage lab queue"),
    ("radiology.queue.manage", "queue", "radiology.manage", "Manage radiology queue"),
    ("blood_bank.queue.manage", "queue", "blood_bank.manage", "Manage blood bank queue"),
    ("inventory.view", "inventory", "view", "View inventory module"),
    ("inventory.manage", "inventory", "manage", "Manage inventory items and suppliers"),
    ("inventory.item.create", "inventory", "item.create", "Create inventory items and suppliers"),
    ("inventory.item.edit", "inventory", "item.edit", "Edit inventory items and suppliers"),
    ("inventory.receive", "inventory", "receive", "Receive inventory stock"),
    ("inventory.issue", "inventory", "issue", "Issue inventory stock"),
    ("inventory.transfer", "inventory", "transfer", "Transfer inventory stock"),
    ("inventory.adjust", "inventory", "adjust", "Adjust inventory stock"),
    ("inventory.stock.receive", "inventory", "stock.receive", "Receive stock into stores"),
    ("inventory.stock.issue", "inventory", "stock.issue", "Issue stock from stores"),
    ("inventory.stock.transfer", "inventory", "stock.transfer", "Transfer stock between stores"),
    ("inventory.stock.adjust", "inventory", "stock.adjust", "Adjust stock balances"),
    ("inventory.purchase", "inventory", "purchase", "Manage purchase requests"),
    ("inventory.requisition.create", "inventory", "requisition.create", "Create store requisitions"),
    ("inventory.requisition.approve", "inventory", "requisition.approve", "Approve and issue store requisitions"),
    ("inventory.requisition.reject", "inventory", "requisition.reject", "Reject store requisitions"),
    ("inventory.reports.view", "inventory", "reports.view", "View inventory reports"),
    ("inventory.report.view", "inventory", "report.view", "View inventory reports"),
    ("inventory.store.manage", "inventory", "store.manage", "Manage central and sub stores"),
    ("inventory.export", "inventory", "export", "Export inventory reports"),
    ("hr.view", "hr", "view", "View HR and payroll module"),
    ("hr.employee.manage", "hr", "employee.manage", "Manage employee profiles, departments, and designations"),
    ("hr.attendance.manage", "hr", "attendance.manage", "Manage attendance and attendance corrections"),
    ("hr.shift.manage", "hr", "shift.manage", "Manage shifts and duty rosters"),
    ("hr.leave.manage", "hr", "leave.manage", "Manage leave requests and balances"),
    ("hr.leave.approve", "hr", "leave.approve", "Approve or reject leave requests"),
    ("hr.payroll.manage", "hr", "payroll.manage", "Manage salary setup, overtime, loans, payroll runs, and payslips"),
    ("hr.payroll.approve", "hr", "payroll.approve", "Approve, finalize, and mark payroll paid"),
    ("payroll.process_salary", "payroll", "process_salary", "Process payroll salary runs"),
    ("payroll.view", "payroll", "view", "View payroll data"),
    ("hr.recruitment.manage", "hr", "recruitment.manage", "Manage recruitment and onboarding"),
    ("hr.performance.manage", "hr", "performance.manage", "Manage performance, appraisal, and disciplinary records"),
    ("hr.exit.manage", "hr", "exit.manage", "Manage resignation, exit, and final settlement"),
    ("hr.documents.manage", "hr", "documents.manage", "Manage HR documents and letters"),
    ("hr.reports.view", "hr", "reports.view", "View HR and payroll reports"),
    ("hr.settings.manage", "hr", "settings.manage", "Manage HR module settings"),
    ("hr.self_service", "hr", "self_service", "Use employee self-service HR features"),
    ("ot.view", "ot", "view", "View OT management module"),
    ("ot.room.manage", "ot", "room.manage", "Manage OT rooms and room status"),
    ("ot.booking.manage", "ot", "booking.manage", "Create and approve OT booking requests"),
    ("ot.schedule.manage", "ot", "schedule.manage", "Schedule surgeries and assign OT staff"),
    ("ot.preop.manage", "ot", "preop.manage", "Manage pre-operative checklist and readiness"),
    ("ot.anesthesia.manage", "ot", "anesthesia.manage", "Manage anesthesia assessment, records, and sign-off"),
    ("ot.surgery.signoff", "ot", "surgery.signoff", "Manage operative notes and surgical sign-off"),
    ("ot.recovery.manage", "ot", "recovery.manage", "Manage post-operative recovery and handover"),
    ("ot.inventory.manage", "ot", "inventory.manage", "Manage OT consumables, equipment, implants, and usage"),
    ("ot.billing.manage", "ot", "billing.manage", "Manage OT billing items and charge summary"),
    ("ot.documents.manage", "ot", "documents.manage", "Manage OT consent, forms, and documents"),
    ("ot.workflow.manage", "ot", "workflow.manage", "Start, complete, cancel, and update surgery workflow status"),
    ("ot.reports.view", "ot", "reports.view", "View OT reports and analytics"),
    ("accounting.view", "accounting", "view", "View accounting"),
    ("accounting.manage", "accounting", "manage", "Manage accounting workflows"),
    ("accounting.approve", "accounting", "approve", "Approve discounts, refunds, expenses, payables, and closings"),
    ("accounting.reports.view", "accounting", "reports.view", "View accounting and finance reports"),
    ("accounting.journal.create", "accounting", "journal.create", "Create accounting journal"),
    ("accounting.journal.post", "accounting", "journal.post", "Post accounting journal"),
    ("accounting.dashboard.view", "accounting", "dashboard.view", "View accounting dashboard"),
    ("accounting.chart_of_accounts.manage", "accounting", "chart_of_accounts.manage", "Manage chart of accounts"),
    ("accounting.ledger.view", "accounting", "ledger.view", "View general ledger"),
    ("accounting.voucher.create", "accounting", "voucher.create", "Create accounting vouchers"),
    ("accounting.voucher.edit", "accounting", "voucher.edit", "Edit draft accounting vouchers"),
    ("accounting.voucher.approve", "accounting", "voucher.approve", "Approve accounting vouchers"),
    ("accounting.voucher.post", "accounting", "voucher.post", "Post accounting vouchers"),
    ("accounting.voucher.reverse", "accounting", "voucher.reverse", "Reverse posted accounting vouchers"),
    ("accounting.expense.create", "accounting", "expense.create", "Create expenses"),
    ("accounting.expense.approve", "accounting", "expense.approve", "Approve expenses"),
    ("accounting.supplier_payment.create", "accounting", "supplier_payment.create", "Create supplier payments"),
    ("accounting.cash_bank.manage", "accounting", "cash_bank.manage", "Manage cash and bank records"),
    ("accounting.report.view", "accounting", "report.view", "View accounting reports"),
    ("accounting.report.export", "accounting", "report.export", "Export accounting reports"),
    ("settings.user.manage", "settings", "user.manage", "Manage users"),
    ("settings.role.manage", "settings", "role.manage", "Manage roles"),
    ("settings.permission.manage", "settings", "permission.manage", "Manage permission catalog"),
    ("admin.manage_users", "admin", "manage_users", "Manage administrative user accounts"),
    ("admin.manage_roles", "admin", "manage_roles", "Manage administrative roles and permissions"),
    ("settings.branch.manage", "settings", "branch.manage", "Manage branches"),
    ("settings.department.manage", "settings", "department.manage", "Manage departments"),
    ("settings.configuration.manage", "settings", "configuration.manage", "Manage hospital configuration builders and setup profiles"),
    ("settings.scope.manage", "settings", "scope.manage", "Manage assignment-level user and role scopes"),
    ("scope.override", "settings", "scope.override", "Use audited emergency or supervisor scope override"),
    ("ipd.scope.all", "ipd", "scope.all", "Access all IPD wards and bed groups within permitted branch"),
    ("inventory.scope.all", "inventory", "scope.all", "Access all stores and inventory scopes within permitted branch"),
    ("queue.scope.all", "queue", "scope.all", "Access all queue scopes and counters within permitted branch"),
    ("laboratory.scope.all", "laboratory", "scope.all", "Access all laboratory sections within permitted branch"),
    ("radiology.scope.all", "radiology", "scope.all", "Access all radiology units within permitted branch"),
    ("blood_bank.scope.all", "blood_bank", "scope.all", "Access all blood bank units within permitted branch"),
    ("audit.view", "audit", "view", "View audit logs"),
]

ROLE_CATALOG = {
    "SUPER_ADMIN": [code for code, *_ in PERMISSION_CATALOG],
    "ADMIN": [code for code, *_ in PERMISSION_CATALOG],
    "DOCTOR": [
        "dashboard.view",
        "patient.view",
        "patient.create",
        "patient.medical_record.update",
        "appointment.view",
        "appointment.book",
        "appointment.manage",
        "opd.view",
        "opd.visit.create",
        "opd.visit.edit",
        "opd.visit.manage",
        "opd.prescribe",
        "ipd.view",
        "ipd.admit",
        "ipd.bed.manage",
        "ipd.transfer",
        "ipd.discharge",
        "ipd.edit_admission",
        "ipd.bed_transfer",
        "ipd.doctor_note.create",
        "ipd.nursing_note.create",
        "ipd.order.create",
        "catering.view",
        "catering.diet_order.create",
        "catering.diet_order.edit",
        "catering.diet_order.approve",
        "catering.report.view",
        "ipd.medication.administer",
        "ipd.handover.create",
        "ipd.handover.acknowledge",
        "ipd.discharge.request",
        "ipd.discharge.approve",
        "ipd.discharge.finalize",
        "ipd.report.print",
        "catering.view",
        "catering.dashboard.view",
        "catering.diet_order.create",
        "catering.meal.deliver",
        "er.view",
        "er.visit.manage",
        "er.triage.manage",
        "er.assignment.manage",
        "er.ambulance.manage",
        "laboratory.view",
        "laboratory.manage",
        "laboratory.order.create",
        "laboratory.result.enter",
        "laboratory.verify_result",
        "laboratory.report.print",
        "radiology.view",
        "radiology.manage",
        "radiology.order.create",
        "radiology.upload_report",
        "radiology.verify_result",
        "radiology.report.print",
        "diagnostics.view",
        "diagnostics.order.manage",
        "reporting.view",
        "ot.view",
        "ot.booking.manage",
        "ot.surgery.signoff",
        "ot.reports.view",
    ],
    "NURSE": [
        "dashboard.view",
        "patient.view",
        "patient.create",
        "appointment.view",
        "opd.view",
        "opd.visit.create",
        "ipd.view",
        "ipd.admit",
        "ipd.transfer",
        "ipd.assign_nurse",
        "ipd.bed_transfer",
        "ipd.nursing_note.create",
        "ipd.medication.administer",
        "ipd.handover.create",
        "ipd.handover.acknowledge",
        "ipd.discharge.request",
        "ipd.report.print",
        "catering.view",
        "catering.dashboard.view",
        "catering.diet_order.create",
        "catering.meal.deliver",
        "er.view",
        "er.visit.manage",
        "er.triage.manage",
        "emergency.view",
        "emergency.register",
        "emergency.triage",
        "emergency.medication.administer",
        "emergency.bed.assign",
        "emergency.status.update",
        "laboratory.view",
        "radiology.view",
    ],
    "DOCTOR_ASSISTANT": [
        "dashboard.view",
        "patient.view",
        "patient.create",
        "patient.id_card.view",
        "patient.id_card.print",
        "appointment.view",
        "appointment.book",
        "appointment.manage",
        "opd.view",
        "opd.visit.create",
        "opd.visit.edit",
        "opd.queue.view",
        "opd.queue.call",
        "laboratory.view",
        "radiology.view",
        "diagnostics.view",
    ],
    "OT_MANAGER": [
        "dashboard.view",
        "patient.view",
        "ipd.view",
        "er.view",
        "ot.view",
        "ot.room.manage",
        "ot.booking.manage",
        "ot.schedule.manage",
        "ot.preop.manage",
        "ot.workflow.manage",
        "ot.documents.manage",
        "ot.reports.view",
        "queue.scope.all",
    ],
    "SURGEON": [
        "dashboard.view",
        "patient.view",
        "ot.view",
        "ot.booking.manage",
        "ot.surgery.signoff",
        "ot.reports.view",
    ],
    "ANESTHETIST": [
        "dashboard.view",
        "patient.view",
        "ot.view",
        "ot.anesthesia.manage",
        "ot.reports.view",
    ],
    "OT_NURSE": [
        "dashboard.view",
        "patient.view",
        "ot.view",
        "ot.preop.manage",
        "ot.recovery.manage",
        "ot.workflow.manage",
        "ot.surgery.signoff",
    ],
    "OT_BILLING_OFFICER": [
        "dashboard.view",
        "patient.view",
        "ot.view",
        "ot.billing.manage",
        "billing.view",
        "billing.invoice.create",
        "billing.payment.collect",
    ],
    "HR_MANAGER": [
        "dashboard.view",
        "patient.view",
        "hr.view",
        "hr.employee.manage",
        "hr.attendance.manage",
        "hr.shift.manage",
        "hr.leave.manage",
        "hr.leave.approve",
        "hr.payroll.manage",
        "payroll.view",
        "payroll.process_salary",
        "hr.recruitment.manage",
        "hr.performance.manage",
        "hr.exit.manage",
        "hr.documents.manage",
        "hr.reports.view",
        "hr.settings.manage",
        "settings.department.manage",
    ],
    "PAYROLL_OFFICER": [
        "dashboard.view",
        "hr.view",
        "hr.payroll.manage",
        "payroll.view",
        "payroll.process_salary",
        "hr.reports.view",
        "accounting.view",
    ],
    "DEPARTMENT_HEAD": [
        "dashboard.view",
        "patient.view",
        "hr.view",
        "hr.attendance.manage",
        "hr.shift.manage",
        "hr.leave.manage",
        "hr.leave.approve",
        "hr.reports.view",
    ],
    "EMPLOYEE": [
        "dashboard.view",
        "hr.view",
        "hr.self_service",
        "hr.leave.manage",
    ],
    "REFERRABLE_DOCTOR": [
        "dashboard.view",
        "patient.view",
        "appointment.view",
        "opd.view",
        "ipd.view",
        "laboratory.view",
        "radiology.view",
        "diagnostics.view",
        "reporting.view",
        "billing.view",
    ],
    "RECEPTIONIST": [
        "dashboard.view",
        "patient.view",
        "patient.create",
        "appointment.view",
        "appointment.book",
        "appointment.manage",
        "appointment.cancel",
        "opd.view",
        "opd.visit.create",
        "opd.visit.edit",
        "billing.view",
        "billing.invoice.create",
        "billing.item.service",
        "billing.item.investigation",
        "billing.payment.collect",
        "billing.sticker.print",
    ],
    "BILLING_STAFF": [
        "dashboard.view",
        "patient.view",
        "billing.view",
        "billing.invoice.create",
        "billing.item.service",
        "billing.item.medicine",
        "billing.item.investigation",
        "billing.payment.collect",
        "billing.payment.refund",
        "billing.sticker.print",
        "reporting.view",
        "diagnostics.view",
        "pharmacy.view",
        "ot.view",
        "ot.billing.manage",
    ],
    "LAB_TECHNICIAN": [
        "dashboard.view",
        "patient.view",
        "laboratory.view",
        "laboratory.manage",
        "laboratory.result.enter",
        "laboratory.verify_result",
        "laboratory.report.print",
        "diagnostics.view",
        "diagnostics.order.manage",
        "inventory.view",
    ],
    "RADIOLOGY_TECHNICIAN": [
        "dashboard.view",
        "patient.view",
        "radiology.view",
        "radiology.manage",
        "radiology.order.create",
        "radiology.upload_image",
        "radiology.upload_report",
        "radiology.verify_result",
        "radiology.report.print",
        "diagnostics.view",
        "diagnostics.order.manage",
    ],
    "INVENTORY_MANAGER": [
        "dashboard.view",
        "inventory.view",
        "inventory.manage",
        "inventory.item.create",
        "inventory.item.edit",
        "inventory.receive",
        "inventory.issue",
        "inventory.transfer",
        "inventory.adjust",
        "inventory.stock.receive",
        "inventory.stock.issue",
        "inventory.stock.transfer",
        "inventory.stock.adjust",
        "inventory.purchase",
        "inventory.requisition.create",
        "inventory.requisition.approve",
        "inventory.requisition.reject",
        "inventory.reports.view",
        "inventory.report.view",
        "inventory.store.manage",
        "inventory.export",
        "pharmacy.view",
        "inventory.scope.all",
    ],
    "INVENTORY_STAFF": [
        "dashboard.view",
        "inventory.view",
        "inventory.receive",
        "inventory.issue",
        "inventory.transfer",
        "inventory.adjust",
        "inventory.stock.receive",
        "inventory.stock.issue",
        "inventory.stock.transfer",
        "inventory.stock.adjust",
        "inventory.requisition.create",
        "inventory.reports.view",
        "inventory.report.view",
    ],
    "BLOOD_BANK_OFFICER": [
        "dashboard.view",
        "patient.view",
        "blood_bank.view",
        "blood_bank.dashboard.view",
        "blood_bank.donor.create",
        "blood_bank.donor.edit",
        "blood_bank.donor.screen",
        "blood_bank.collection.create",
        "blood_bank.testing.update",
        "blood_bank.component.prepare",
        "blood_bank.stock.view",
        "blood_bank.request.create",
        "blood_bank.request.approve",
        "blood_bank.crossmatch.perform",
        "blood_bank.crossmatch.verify",
        "blood_bank.issue",
        "blood_bank.return",
        "blood_bank.discard",
        "blood_bank.transfusion.update",
        "blood_bank.report.view",
        "blood_bank.report.export",
        "blood_bank.scope.all",
        "catering.view",
        "catering.dashboard.view",
        "catering.report.view",
    ],
    "PATIENT": [
        "patient.portal.view",
    ],
    "PHARMACIST": [
        "dashboard.view",
        "patient.view",
        "pharmacy.view",
        "pharmacy.dispense",
        "pharmacy.sale.create",
        "pharmacy.return",
        "pharmacy.stock.adjust",
        "pharmacy.purchase.manage",
        "pharmacy.settings.manage",
    ],
    "DIETITIAN": [
        "dashboard.view",
        "patient.view",
        "ipd.view",
        "er.view",
        "catering.view",
        "catering.dashboard.view",
        "catering.diet_order.create",
        "catering.diet_order.edit",
        "catering.diet_order.approve",
        "catering.kitchen_queue.view",
        "catering.report.view",
        "catering.report.export",
    ],
    "KITCHEN_STAFF": [
        "dashboard.view",
        "catering.view",
        "catering.dashboard.view",
        "catering.kitchen_queue.view",
        "catering.meal.prepare",
        "catering.meal.deliver",
        "catering.meal.cancel",
        "catering.staff_meal.manage",
        "catering.report.view",
    ],
    "ACCOUNTANT": [
        "dashboard.view",
        "billing.view",
        "billing.invoice.create",
        "billing.item.service",
        "billing.item.medicine",
        "billing.item.investigation",
        "billing.invoice.void",
        "billing.payment.collect",
        "billing.payment.refund",
        "billing.sticker.print",
        "billing.service.manage",
        "billing.doctor.manage",
        "reporting.view",
        "reporting.financial.view",
        "reporting.export",
        "accounting.view",
        "accounting.manage",
        "accounting.approve",
        "accounting.reports.view",
        "accounting.journal.create",
        "accounting.journal.post",
        "accounting.dashboard.view",
        "accounting.chart_of_accounts.manage",
        "accounting.ledger.view",
        "accounting.voucher.create",
        "accounting.voucher.edit",
        "accounting.voucher.approve",
        "accounting.voucher.post",
        "accounting.voucher.reverse",
        "accounting.expense.create",
        "accounting.expense.approve",
        "accounting.supplier_payment.create",
        "accounting.cash_bank.manage",
        "accounting.report.view",
        "accounting.report.export",
        "diagnostics.view",
        "hr.view",
        "hr.payroll.manage",
        "payroll.view",
        "payroll.process_salary",
        "hr.reports.view",
        "ot.view",
        "ot.billing.manage",
        "ot.reports.view",
        "queue.scope.all",
    ],
    "MANAGEMENT": [
        "dashboard.view",
        "patient.view",
        "appointment.view",
        "opd.view",
        "ipd.view",
        "er.view",
        "laboratory.view",
        "radiology.view",
        "pharmacy.view",
        "inventory.view",
        "blood_bank.view",
        "hr.view",
        "payroll.view",
        "ot.view",
        "billing.view",
        "accounting.view",
        "accounting.dashboard.view",
        "reporting.view",
        "reporting.financial.view",
        "reporting.export",
        "notification.view",
        "queue.view",
        "queue.scope.all",
        "ipd.scope.all",
        "inventory.scope.all",
        "laboratory.scope.all",
        "radiology.scope.all",
        "blood_bank.scope.all",
    ],
}

for role_code, permissions in ROLE_CATALOG.items():
    if role_code != "PATIENT" and "scanner.use" not in permissions:
        permissions.append("scanner.use")
    if role_code != "PATIENT" and "ai.assistant.use" not in permissions:
        permissions.append("ai.assistant.use")
    if role_code != "PATIENT" and "notification.view" not in permissions:
        permissions.append("notification.view")
    if role_code != "PATIENT" and "notification.action" not in permissions:
        permissions.append("notification.action")
    if role_code != "PATIENT" and "queue.view" not in permissions:
        permissions.append("queue.view")
    if role_code != "PATIENT" and any(code in permissions for code in ("opd.view", "appointment.view")):
        for permission_code in ("opd.queue.view", "opd.queue.call"):
            if permission_code not in permissions:
                permissions.append(permission_code)
    if role_code != "PATIENT" and "billing.view" in permissions and "billing.queue.manage" not in permissions:
        permissions.append("billing.queue.manage")
    if role_code != "PATIENT" and "pharmacy.view" in permissions and "pharmacy.queue.manage" not in permissions:
        permissions.append("pharmacy.queue.manage")
    if role_code != "PATIENT" and "laboratory.view" in permissions and "lab.queue.manage" not in permissions:
        permissions.append("lab.queue.manage")
    if role_code != "PATIENT" and "radiology.view" in permissions and "radiology.queue.manage" not in permissions:
        permissions.append("radiology.queue.manage")
    if role_code != "PATIENT" and "blood_bank.view" in permissions and "blood_bank.queue.manage" not in permissions:
        permissions.append("blood_bank.queue.manage")
    if role_code != "PATIENT" and "catering.view" in permissions and "catering.kitchen_queue.view" not in permissions:
        permissions.append("catering.kitchen_queue.view")
    if role_code != "PATIENT":
        for permission_code in ("patient.id_card.view", "patient.id_card.generate", "patient.id_card.print", "patient.id_card.reprint"):
            if "patient.view" in permissions and permission_code not in permissions:
                permissions.append(permission_code)
for admin_role in ("SUPER_ADMIN", "ADMIN"):
    for permission_code in ("scanner.generate", "scanner.settings.manage", "scanner.audit.view", "patient.id_card.configure", "ai.assistant.action", "ai.assistant.configure", "ai.assistant.audit.view", "notification.configure", "notification.audit.view", "queue.call_next", "queue.skip", "queue.recall", "queue.transfer", "queue.priority.update", "queue.counter.manage", "queue.display.manage", "settings.scope.manage", "scope.override", "ipd.scope.all", "inventory.scope.all", "queue.scope.all", "laboratory.scope.all", "radiology.scope.all", "blood_bank.scope.all"):
        if permission_code not in ROLE_CATALOG[admin_role]:
            ROLE_CATALOG[admin_role].append(permission_code)

ROLE_FLAGS = {
    "SUPER_ADMIN": {"is_doctor_role": False, "is_referral_role": False},
    "ADMIN": {"is_doctor_role": False, "is_referral_role": False},
    "DOCTOR": {"is_doctor_role": True, "is_referral_role": True},
    "NURSE": {"is_doctor_role": False, "is_referral_role": False},
    "DOCTOR_ASSISTANT": {"is_doctor_role": False, "is_referral_role": False},
    "REFERRABLE_DOCTOR": {"is_doctor_role": True, "is_referral_role": True},
    "PHARMACIST": {"is_doctor_role": False, "is_referral_role": False},
    "DIETITIAN": {"is_doctor_role": False, "is_referral_role": False},
    "KITCHEN_STAFF": {"is_doctor_role": False, "is_referral_role": False},
    "ACCOUNTANT": {"is_doctor_role": False, "is_referral_role": False},
    "BILLING_STAFF": {"is_doctor_role": False, "is_referral_role": False},
    "MANAGEMENT": {"is_doctor_role": False, "is_referral_role": False},
    "RECEPTIONIST": {"is_doctor_role": False, "is_referral_role": False},
    "LAB_TECHNICIAN": {"is_doctor_role": False, "is_referral_role": False},
    "RADIOLOGY_TECHNICIAN": {"is_doctor_role": False, "is_referral_role": False},
    "INVENTORY_MANAGER": {"is_doctor_role": False, "is_referral_role": False},
    "INVENTORY_STAFF": {"is_doctor_role": False, "is_referral_role": False},
    "BLOOD_BANK_OFFICER": {"is_doctor_role": False, "is_referral_role": False},
    "HR_MANAGER": {"is_doctor_role": False, "is_referral_role": False},
    "PAYROLL_OFFICER": {"is_doctor_role": False, "is_referral_role": False},
    "DEPARTMENT_HEAD": {"is_doctor_role": False, "is_referral_role": False},
    "EMPLOYEE": {"is_doctor_role": False, "is_referral_role": False},
    "OT_MANAGER": {"is_doctor_role": False, "is_referral_role": False},
    "SURGEON": {"is_doctor_role": True, "is_referral_role": True},
    "ANESTHETIST": {"is_doctor_role": True, "is_referral_role": False},
    "OT_NURSE": {"is_doctor_role": False, "is_referral_role": False},
    "OT_BILLING_OFFICER": {"is_doctor_role": False, "is_referral_role": False},
    "PATIENT": {"is_doctor_role": False, "is_referral_role": False},
}
