PERMISSION_CATALOG = [
    ("dashboard.view", "dashboard", "view", "View dashboard"),
    ("patient.view", "patient", "view", "View patients"),
    ("patient.create", "patient", "create", "Create patients"),
    ("patient.portal.view", "patient", "portal.view", "Access patient portal"),
    ("patient.edit", "patient", "edit", "Edit patients"),
    ("patient.delete", "patient", "delete", "Delete patients"),
    ("appointment.view", "appointment", "view", "View appointments"),
    ("appointment.book", "appointment", "book", "Book appointments"),
    ("appointment.manage", "appointment", "manage", "Manage and check in appointments"),
    ("billing.view", "billing", "view", "View billing"),
    ("billing.invoice.create", "billing", "invoice.create", "Create billing invoices"),
    ("billing.invoice.void", "billing", "invoice.void", "Void billing invoices"),
    ("billing.service.manage", "billing", "service.manage", "Manage billing services"),
    ("billing.doctor.manage", "billing", "doctor.manage", "Manage referred doctors"),
    ("opd.view", "opd", "view", "View OPD module"),
    ("opd.visit.manage", "opd", "visit.manage", "Manage OPD visits"),
    ("ipd.view", "ipd", "view", "View IPD module"),
    ("ipd.admission.manage", "ipd", "admission.manage", "Manage IPD admissions"),
    ("ipd.bed.manage", "ipd", "bed.manage", "Manage IPD beds"),
    ("laboratory.view", "laboratory", "view", "View laboratory"),
    ("laboratory.manage", "laboratory", "manage", "Manage laboratory worklist and results"),
    ("radiology.view", "radiology", "view", "View radiology"),
    ("radiology.manage", "radiology", "manage", "Manage radiology worklist and results"),
    ("reporting.view", "reporting", "view", "View reporting"),
    ("pharmacy.view", "pharmacy", "view", "View pharmacy module"),
    ("pharmacy.dispense", "pharmacy", "dispense", "Dispense medicine"),
    ("pharmacy.stock.adjust", "pharmacy", "stock.adjust", "Adjust pharmacy stock"),
    ("accounting.view", "accounting", "view", "View accounting"),
    ("accounting.journal.create", "accounting", "journal.create", "Create accounting journal"),
    ("accounting.journal.post", "accounting", "journal.post", "Post accounting journal"),
    ("settings.user.manage", "settings", "user.manage", "Manage users"),
    ("settings.role.manage", "settings", "role.manage", "Manage roles"),
    ("settings.permission.manage", "settings", "permission.manage", "Manage permission catalog"),
    ("settings.branch.manage", "settings", "branch.manage", "Manage branches"),
    ("settings.department.manage", "settings", "department.manage", "Manage departments"),
    ("audit.view", "audit", "view", "View audit logs"),
]

ROLE_CATALOG = {
    "SUPER_ADMIN": [code for code, *_ in PERMISSION_CATALOG],
    "ADMIN": [
        "dashboard.view",
        "patient.view",
        "patient.create",
        "billing.view",
        "billing.invoice.create",
        "billing.invoice.void",
        "billing.service.manage",
        "billing.doctor.manage",
        "opd.view",
        "opd.visit.manage",
        "ipd.view",
        "ipd.admission.manage",
        "ipd.bed.manage",
        "laboratory.view",
        "laboratory.manage",
        "radiology.view",
        "radiology.manage",
        "reporting.view",
        "pharmacy.view",
        "accounting.view",
        "settings.user.manage",
        "settings.role.manage",
        "settings.branch.manage",
        "settings.department.manage",
        "audit.view",
        "appointment.view",
        "appointment.manage",
    ],
    "DOCTOR": [
        "dashboard.view",
        "patient.view",
        "patient.create",
        "appointment.view",
        "appointment.manage",
        "opd.view",
        "opd.visit.manage",
        "ipd.view",
        "ipd.bed.manage",
        "laboratory.view",
        "laboratory.manage",
        "radiology.view",
        "radiology.manage",
        "reporting.view",
    ],
    "REFERRABLE_DOCTOR": [
        "dashboard.view",
        "patient.view",
        "appointment.view",
        "opd.view",
        "ipd.view",
        "laboratory.view",
        "radiology.view",
        "reporting.view",
        "billing.view",
    ],
    "PATIENT": [
        "patient.portal.view",
        "appointment.view",
        "appointment.book",
    ],
    "PHARMACIST": ["dashboard.view", "patient.view", "pharmacy.view", "pharmacy.dispense"],
    "ACCOUNTANT": [
        "dashboard.view",
        "billing.view",
        "billing.invoice.create",
        "billing.invoice.void",
        "billing.service.manage",
        "billing.doctor.manage",
        "reporting.view",
        "accounting.view",
        "accounting.journal.create",
        "accounting.journal.post",
    ],
}

ROLE_FLAGS = {
    "SUPER_ADMIN": {"is_doctor_role": False, "is_referral_role": False},
    "ADMIN": {"is_doctor_role": False, "is_referral_role": False},
    "DOCTOR": {"is_doctor_role": True, "is_referral_role": True},
    "REFERRABLE_DOCTOR": {"is_doctor_role": True, "is_referral_role": True},
    "PHARMACIST": {"is_doctor_role": False, "is_referral_role": False},
    "ACCOUNTANT": {"is_doctor_role": False, "is_referral_role": False},
    "PATIENT": {"is_doctor_role": False, "is_referral_role": False},
}
