"""Create OT management module tables.

Revision ID: 20260429_0032
Revises: 20260429_0031
Create Date: 2026-04-29 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260429_0032"
down_revision = "20260429_0031"
branch_labels = None
depends_on = None


def base_columns():
    return [
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("updated_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    ]


def upgrade():
    op.create_table(
        "ot_rooms",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("room_number", sa.String(50), nullable=False),
        sa.Column("name", sa.String(150), nullable=False),
        sa.Column("room_type", sa.String(60), nullable=False, server_default="major"),
        sa.Column("status", sa.String(40), nullable=False, server_default="available"),
        sa.Column("floor", sa.String(60), nullable=True),
        sa.Column("equipment_summary", sa.Text(), nullable=True),
        sa.Column("hourly_charge", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ot_bookings",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("patient_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source_module", sa.String(40), nullable=True),
        sa.Column("source_reference_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("booking_number", sa.String(60), nullable=False),
        sa.Column("procedure_name", sa.String(200), nullable=False),
        sa.Column("surgery_type", sa.String(60), nullable=False, server_default="elective"),
        sa.Column("priority_level", sa.String(40), nullable=False, server_default="normal"),
        sa.Column("preferred_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("estimated_duration_minutes", sa.Integer(), nullable=False, server_default="60"),
        sa.Column("department_name", sa.String(120), nullable=True),
        sa.Column("diagnosis", sa.Text(), nullable=True),
        sa.Column("requested_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("status", sa.String(40), nullable=False, server_default="requested"),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"]),
        sa.ForeignKeyConstraint(["requested_by_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_number"),
    )
    op.create_index("ix_ot_bookings_booking_number", "ot_bookings", ["booking_number"])
    op.create_table(
        "surgery_schedules",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("booking_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("room_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("scheduled_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("primary_surgeon_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("assistant_surgeon_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("anesthetist_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("scrub_nurse_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("circulating_nurse_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("technician_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("status", sa.String(40), nullable=False, server_default="scheduled"),
        sa.Column("patient_shifted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("surgery_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("surgery_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("room_entry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("room_exit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delay_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["booking_id"], ["ot_bookings.id"]),
        sa.ForeignKeyConstraint(["room_id"], ["ot_rooms.id"]),
        sa.ForeignKeyConstraint(["primary_surgeon_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["assistant_surgeon_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["anesthetist_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["scrub_nurse_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["circulating_nurse_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["technician_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "scheduled_start_at", "scheduled_end_at", name="uq_ot_room_exact_slot"),
    )
    op.create_table(
        "surgery_team_assignments",
        *base_columns(),
        sa.Column("schedule_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("role", sa.String(80), nullable=False),
        sa.Column("staff_name", sa.String(150), nullable=True),
        sa.Column("response_status", sa.String(40), nullable=False, server_default="assigned"),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["schedule_id"], ["surgery_schedules.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pre_op_checklists",
        *base_columns(),
        sa.Column("schedule_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("consent_signed", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("anesthesia_cleared", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("lab_verified", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("radiology_verified", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("blood_arranged", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("npo_confirmed", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("site_marked", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("equipment_confirmed", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("implant_confirmed", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("allergy_info", sa.Text(), nullable=True),
        sa.Column("current_medication_review", sa.Text(), nullable=True),
        sa.Column("pre_op_diagnosis", sa.Text(), nullable=True),
        sa.Column("risk_assessment_notes", sa.Text(), nullable=True),
        sa.Column("ready_for_ot", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("checked_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["schedule_id"], ["surgery_schedules.id"]),
        sa.ForeignKeyConstraint(["checked_by_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_id"),
    )
    op.create_table(
        "anesthesia_records",
        *base_columns(),
        sa.Column("schedule_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("anesthesia_type", sa.String(60), nullable=False, server_default="general"),
        sa.Column("pre_assessment", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("anesthesia_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("anesthesia_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("medication_record", sa.Text(), nullable=True),
        sa.Column("fluid_record", sa.Text(), nullable=True),
        sa.Column("vitals_summary", sa.Text(), nullable=True),
        sa.Column("complications", sa.Text(), nullable=True),
        sa.Column("recovery_notes", sa.Text(), nullable=True),
        sa.Column("clearance_status", sa.String(40), nullable=False, server_default="pending"),
        sa.Column("signed_off_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("signed_off_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["schedule_id"], ["surgery_schedules.id"]),
        sa.ForeignKeyConstraint(["signed_off_by_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_id"),
    )
    op.create_table(
        "surgery_notes",
        *base_columns(),
        sa.Column("schedule_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("procedure_performed", sa.Text(), nullable=True),
        sa.Column("operative_findings", sa.Text(), nullable=True),
        sa.Column("surgeon_notes", sa.Text(), nullable=True),
        sa.Column("nursing_notes", sa.Text(), nullable=True),
        sa.Column("instrument_count_confirmed", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("sponge_count_confirmed", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("implant_usage_details", sa.Text(), nullable=True),
        sa.Column("specimen_collection_details", sa.Text(), nullable=True),
        sa.Column("surgery_outcome", sa.String(80), nullable=False, server_default="successful"),
        sa.Column("surgeon_signed_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("anesthetist_signed_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("nurse_signed_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("signed_off_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["schedule_id"], ["surgery_schedules.id"]),
        sa.ForeignKeyConstraint(["surgeon_signed_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["anesthetist_signed_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["nurse_signed_by_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_id"),
    )
    op.create_table(
        "post_op_recovery",
        *base_columns(),
        sa.Column("schedule_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("transfer_to", sa.String(80), nullable=False, server_default="recovery"),
        sa.Column("recovery_admission_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("vitals_summary", sa.Text(), nullable=True),
        sa.Column("pain_score", sa.Integer(), nullable=True),
        sa.Column("consciousness_status", sa.String(120), nullable=True),
        sa.Column("post_op_instructions", sa.Text(), nullable=True),
        sa.Column("medication_instructions", sa.Text(), nullable=True),
        sa.Column("nursing_observations", sa.Text(), nullable=True),
        sa.Column("recovery_discharge_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("handover_notes", sa.Text(), nullable=True),
        sa.Column("complication_summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["schedule_id"], ["surgery_schedules.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_id"),
    )
    op.create_table(
        "ot_consumable_usage",
        *base_columns(),
        sa.Column("schedule_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("inventory_item_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("item_name", sa.String(180), nullable=False),
        sa.Column("batch_no", sa.String(100), nullable=True),
        sa.Column("quantity_used", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("quantity_returned", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("wastage_quantity", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("unit_cost", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("charged_amount", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["schedule_id"], ["surgery_schedules.id"]),
        sa.ForeignKeyConstraint(["inventory_item_id"], ["inventory_items.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ot_equipment_usage",
        *base_columns(),
        sa.Column("schedule_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("equipment_name", sa.String(180), nullable=False),
        sa.Column("usage_notes", sa.Text(), nullable=True),
        sa.Column("charge_amount", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("confirmed", sa.Boolean(), nullable=False, server_default="false"),
        sa.ForeignKeyConstraint(["schedule_id"], ["surgery_schedules.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ot_billing_items",
        *base_columns(),
        sa.Column("schedule_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("billing_invoice_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("charge_type", sa.String(80), nullable=False),
        sa.Column("description", sa.String(200), nullable=False),
        sa.Column("amount", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("payment_status", sa.String(40), nullable=False, server_default="pending"),
        sa.ForeignKeyConstraint(["schedule_id"], ["surgery_schedules.id"]),
        sa.ForeignKeyConstraint(["billing_invoice_id"], ["billing_invoices.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ot_documents",
        *base_columns(),
        sa.Column("schedule_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("document_type", sa.String(80), nullable=False),
        sa.Column("title", sa.String(180), nullable=False),
        sa.Column("file_url", sa.String(500), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("status", sa.String(40), nullable=False, server_default="stored"),
        sa.ForeignKeyConstraint(["schedule_id"], ["surgery_schedules.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ot_audit_logs",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.String(120), nullable=False),
        sa.Column("entity_type", sa.String(80), nullable=False),
        sa.Column("entity_id", sa.String(80), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade():
    for table in [
        "ot_audit_logs",
        "ot_documents",
        "ot_billing_items",
        "ot_equipment_usage",
        "ot_consumable_usage",
        "post_op_recovery",
        "surgery_notes",
        "anesthesia_records",
        "pre_op_checklists",
        "surgery_team_assignments",
        "surgery_schedules",
        "ot_bookings",
        "ot_rooms",
    ]:
        op.drop_table(table)
