"""Create HR and payroll module tables.

Revision ID: 20260429_0031
Revises: 20260428_0030, 20260425_0029
Create Date: 2026-04-29 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260429_0031"
down_revision = ("20260428_0030", "20260425_0029")
branch_labels = None
depends_on = None


def base_columns():
    return [
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("updated_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    ]


def upgrade():
    op.create_table(
        "hr_designations",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("department_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(150), nullable=False),
        sa.Column("code", sa.String(50), nullable=True),
        sa.Column("grade", sa.String(50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_employees",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("staff_code", sa.String(50), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("department_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("designation_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("reporting_manager_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("full_name", sa.String(160), nullable=False),
        sa.Column("photo_url", sa.String(500), nullable=True),
        sa.Column("gender", sa.String(30), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("phone", sa.String(30), nullable=True),
        sa.Column("email", sa.String(120), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("national_id", sa.String(80), nullable=True),
        sa.Column("passport_number", sa.String(80), nullable=True),
        sa.Column("employee_type", sa.String(60), nullable=False, server_default="full_time"),
        sa.Column("employee_category", sa.String(60), nullable=False, server_default="other"),
        sa.Column("joining_date", sa.Date(), nullable=False),
        sa.Column("employment_status", sa.String(40), nullable=False, server_default="active"),
        sa.Column("qualification", sa.Text(), nullable=True),
        sa.Column("specialization", sa.String(160), nullable=True),
        sa.Column("license_number", sa.String(120), nullable=True),
        sa.Column("license_expiry_date", sa.Date(), nullable=True),
        sa.Column("emergency_contact_name", sa.String(160), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(30), nullable=True),
        sa.Column("bank_name", sa.String(160), nullable=True),
        sa.Column("bank_account_name", sa.String(160), nullable=True),
        sa.Column("bank_account_number", sa.String(80), nullable=True),
        sa.Column("tax_id", sa.String(80), nullable=True),
        sa.Column("contract_end_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"]),
        sa.ForeignKeyConstraint(["designation_id"], ["hr_designations.id"]),
        sa.ForeignKeyConstraint(["reporting_manager_id"], ["hr_employees.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("staff_code"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_hr_employees_staff_code", "hr_employees", ["staff_code"])
    op.create_table(
        "hr_employee_documents",
        *base_columns(),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("document_type", sa.String(80), nullable=False),
        sa.Column("file_name", sa.String(220), nullable=True),
        sa.Column("file_url", sa.String(500), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_attendance",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("attendance_date", sa.Date(), nullable=False),
        sa.Column("check_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("check_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(40), nullable=False, server_default="present"),
        sa.Column("working_hours", sa.Numeric(8, 2), nullable=False, server_default="0"),
        sa.Column("late_minutes", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("early_leave_minutes", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("correction_status", sa.String(40), nullable=True),
        sa.Column("correction_note", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "attendance_date", name="uq_hr_attendance_employee_date"),
    )
    op.create_table(
        "hr_shifts",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("code", sa.String(50), nullable=False),
        sa.Column("shift_type", sa.String(60), nullable=False, server_default="morning"),
        sa.Column("start_time", sa.String(10), nullable=False),
        sa.Column("end_time", sa.String(10), nullable=False),
        sa.Column("break_minutes", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("allowance_amount", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_duty_rosters",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("shift_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("roster_date", sa.Date(), nullable=False),
        sa.Column("duty_area", sa.String(120), nullable=True),
        sa.Column("duty_type", sa.String(60), nullable=False, server_default="regular"),
        sa.Column("status", sa.String(40), nullable=False, server_default="assigned"),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.ForeignKeyConstraint(["shift_id"], ["hr_shifts.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "roster_date", "shift_id", name="uq_hr_roster_employee_shift_date"),
    )
    op.create_table(
        "hr_leave_types",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("code", sa.String(50), nullable=False),
        sa.Column("annual_quota", sa.Numeric(6, 2), nullable=False, server_default="0"),
        sa.Column("is_paid", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("requires_approval", sa.Boolean(), nullable=False, server_default="true"),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_leave_requests",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("leave_type_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("number_of_days", sa.Numeric(6, 2), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(40), nullable=False, server_default="pending"),
        sa.Column("approved_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("approval_remarks", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.ForeignKeyConstraint(["leave_type_id"], ["hr_leave_types.id"]),
        sa.ForeignKeyConstraint(["approved_by_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_salary_structures",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("basic_salary", sa.Numeric(12, 2), nullable=False),
        sa.Column("house_rent_allowance", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("medical_allowance", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("transport_allowance", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("food_allowance", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("night_duty_allowance", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("on_call_allowance", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("emergency_duty_allowance", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("overtime_hourly_rate", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("bonus_incentive", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("tax_deduction", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("provident_fund_deduction", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("other_deductions", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id"),
    )
    op.create_table(
        "hr_overtime_requests",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("overtime_date", sa.Date(), nullable=False),
        sa.Column("overtime_hours", sa.Numeric(8, 2), nullable=False),
        sa.Column("overtime_type", sa.String(60), nullable=False, server_default="regular"),
        sa.Column("status", sa.String(40), nullable=False, server_default="pending"),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("approved_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.ForeignKeyConstraint(["approved_by_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_employee_loans",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("loan_type", sa.String(60), nullable=False, server_default="advance"),
        sa.Column("approved_amount", sa.Numeric(12, 2), nullable=False),
        sa.Column("monthly_installment", sa.Numeric(12, 2), nullable=False),
        sa.Column("deduction_start_month", sa.String(7), nullable=False),
        sa.Column("remaining_balance", sa.Numeric(12, 2), nullable=False),
        sa.Column("status", sa.String(40), nullable=False, server_default="active"),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_payroll_runs",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("department_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("payroll_month", sa.String(7), nullable=False),
        sa.Column("status", sa.String(40), nullable=False, server_default="draft"),
        sa.Column("total_employees", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("total_gross_salary", sa.Numeric(14, 2), nullable=False, server_default="0"),
        sa.Column("total_deductions", sa.Numeric(14, 2), nullable=False, server_default="0"),
        sa.Column("total_net_salary", sa.Numeric(14, 2), nullable=False, server_default="0"),
        sa.Column("approved_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"]),
        sa.ForeignKeyConstraint(["approved_by_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("branch_id", "payroll_month", "department_id", name="uq_hr_payroll_month_department"),
    )
    op.create_table(
        "hr_payroll_items",
        *base_columns(),
        sa.Column("payroll_run_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("payroll_month", sa.String(7), nullable=False),
        sa.Column("present_days", sa.Numeric(6, 2), nullable=False, server_default="0"),
        sa.Column("absent_days", sa.Numeric(6, 2), nullable=False, server_default="0"),
        sa.Column("late_days", sa.Numeric(6, 2), nullable=False, server_default="0"),
        sa.Column("unpaid_leave_days", sa.Numeric(6, 2), nullable=False, server_default="0"),
        sa.Column("overtime_hours", sa.Numeric(8, 2), nullable=False, server_default="0"),
        sa.Column("basic_salary", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("total_allowances", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("overtime_amount", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("gross_salary", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("tax_deduction", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("provident_fund_deduction", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("loan_deduction", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("attendance_deduction", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("other_deductions", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("total_deductions", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("net_salary", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("payment_status", sa.String(40), nullable=False, server_default="unpaid"),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("calculation_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["payroll_run_id"], ["hr_payroll_runs.id"]),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_recruitment_jobs",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("department_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("title", sa.String(160), nullable=False),
        sa.Column("number_of_positions", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("status", sa.String(40), nullable=False, server_default="open"),
        sa.Column("closing_date", sa.Date(), nullable=True),
        sa.Column("salary_range", sa.String(120), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_candidates",
        *base_columns(),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("full_name", sa.String(160), nullable=False),
        sa.Column("phone", sa.String(30), nullable=True),
        sa.Column("email", sa.String(120), nullable=True),
        sa.Column("status", sa.String(40), nullable=False, server_default="applied"),
        sa.Column("interview_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["hr_recruitment_jobs.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_performance_reviews",
        *base_columns(),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("review_period", sa.String(20), nullable=False),
        sa.Column("rating", sa.Numeric(3, 1), nullable=False, server_default="3"),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("kpi_summary", sa.Text(), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_resignations",
        *base_columns(),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("resignation_date", sa.Date(), nullable=False),
        sa.Column("last_working_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(40), nullable=False, server_default="applied"),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("exit_interview_note", sa.Text(), nullable=True),
        sa.Column("final_settlement_amount", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("clearance_status", sa.String(40), nullable=False, server_default="pending"),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_letters",
        *base_columns(),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("letter_type", sa.String(80), nullable=False),
        sa.Column("title", sa.String(180), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(40), nullable=False, server_default="draft"),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_settings",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("setting_key", sa.String(100), nullable=False),
        sa.Column("setting_value", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("branch_id", "setting_key", name="uq_hr_settings_branch_key"),
    )
    op.create_table(
        "hr_audit_logs",
        *base_columns(),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.String(120), nullable=False),
        sa.Column("entity_type", sa.String(80), nullable=False),
        sa.Column("entity_id", sa.String(80), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade():
    for table in [
        "hr_audit_logs",
        "hr_settings",
        "hr_letters",
        "hr_resignations",
        "hr_performance_reviews",
        "hr_candidates",
        "hr_recruitment_jobs",
        "hr_payroll_items",
        "hr_payroll_runs",
        "hr_employee_loans",
        "hr_overtime_requests",
        "hr_salary_structures",
        "hr_leave_requests",
        "hr_leave_types",
        "hr_duty_rosters",
        "hr_shifts",
        "hr_attendance",
        "hr_employee_documents",
        "hr_employees",
        "hr_designations",
    ]:
        op.drop_table(table)
